name: Build

on: [push, pull_request]

permissions: {}

jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
            bin_extension: .exe
          - name: macos
            os: macos-latest

    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@fcf085fcb4b4b8f63f96906cd713eb52181b5ea4
        with:
          toolchain: 1.85.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6

      - name: Install dependencies (linux)
        run: sudo apt-get -y install libgtk-3-dev libasound2-dev
        if: matrix.name == 'linux'

      - name: Build
        run: cargo build --release --locked --bins
        env:
          CARGO_PROFILE_RELEASE_LTO: "true"

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: bff-${{ matrix.name }}-${{ github.sha }}
          path: |
            ./target/release/bff-cli${{ matrix.bin_extension }}
            ./target/release/bff-gui${{ matrix.bin_extension }}
